name: Challenge 4
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout Repo
         uses: actions/checkout@v2
      -  name: test python script
         run: python3 hello.py
  checkout:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      -  name: Checkout Repo
         uses: actions/checkout@v2
      -  name: Create Artifact
         uses: actions/upload-artifact@v4
         with:
           name: Hello World
           path: .
         
    
